java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
Since getCurrentActivity() is null, it cannot fetch view and gives an error. This was fixed by checking the issue. and the minimum pack was kept as 21.